AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/rybit/client.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/rybit/client.rb'

Naming/AccessorMethodName:
  Enabled: false
